from log_utils import log_event

def simulate_ai_library_agent(user, question):
    # Data Layer
    log_event("Data Layer", f"Loaded users_profiles.csv successfully for user: {user['name']}")

    # Intent Detection
    if "borrow" in question.lower():
        intent = "borrow"
    else:
        intent = "unknown"
    log_event("Intent Detection", f"Detected intent: {intent}")

    # Prompt Layer
    prompt = f"User: {user['name']}\nQuestion: {question}"
    log_event("Prompt Layer", "Final prompt sent to GPT")

    # AI Layer
    answer = f"Simulated GPT answer for: {question}"
    log_event("AI Layer", f"Response generated by GPT: {answer[:50]}")

    # Governance Layer
    log_event("Governance Layer", f"Logged interaction for user: {user['name']}")

    return answer

# Example call for demonstration
if __name__ == "__main__":
    user = {"name": "Ahmed", "preferred_language": "Arabic"}
    question = "Can I borrow a book?"
    print(simulate_ai_library_agent(user, question))
